# Generated by Django 4.1 on 2022-11-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustom',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=600, null=True, verbose_name='Descripción'),
        ),
    ]
