# Generated by Django 4.1 on 2022-11-28 19:45

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuariocustom_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustom',
            name='image',
            field=models.ImageField(default='default/usuario.jpg', max_length=255, upload_to=usuarios.models.UsuarioCustom.image_upload_to),
        ),
    ]
