# Generated by Django 4.1 on 2022-11-28 02:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, default='', max_length=200)),
                ('campo', models.SlugField(unique=True, verbose_name='Campo')),
                ('publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicacion ')),
            ],
            options={
                'verbose_name_plural': 'Grupos',
                'ordering': ['-publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, default='', max_length=200)),
                ('articulo_campo', models.SlugField(unique=True, verbose_name='Campo de articulo')),
                ('contenido', tinymce.models.HTMLField(blank=True, default='')),
                ('notas', tinymce.models.HTMLField(blank=True, default='')),
                ('publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicacion ')),
                ('modificacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de modificacion')),
                ('grupo', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='principal.grupoarticulo', verbose_name='Grupos')),
            ],
            options={
                'verbose_name_plural': 'Articulo',
                'ordering': ['-publicacion'],
            },
        ),
    ]
