# Generated by Django 4.1 on 2022-11-28 19:33

from django.db import migrations, models
import principal.models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_articulo_autor_grupoarticulo_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='image',
            field=models.ImageField(default='default/no_imagen.png', max_length=255, upload_to=principal.models.Articulo.image_upload_to),
        ),
        migrations.AddField(
            model_name='grupoarticulo',
            name='image',
            field=models.ImageField(default='default/no_imagen.png', max_length=255, upload_to=principal.models.GrupoArticulo.image_upload_to),
        ),
    ]
