# Generated by Django 4.1 on 2022-11-28 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0004_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, default='', max_length=200)),
                ('contenido', tinymce.models.HTMLField(blank=True, default='')),
                ('autor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='principal.grupoarticulo', verbose_name='Grupos')),
            ],
            options={
                'verbose_name_plural': 'Genero',
            },
        ),
        migrations.CreateModel(
            name='creador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('biografia', tinymce.models.HTMLField(blank=True, default='')),
                ('grupo', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='principal.grupoarticulo', verbose_name='Grupos')),
            ],
            options={
                'verbose_name_plural': 'Creador',
            },
        ),
    ]
